In [170]:
import numpy as np
def perceptron(X, y):
    X = np.insert(X, X.shape[1], 1, axis=1)
    weights = np.ones(X.shape[1])
    lr = 0.5
    for i in range(5000):
        y_hat = sigmoid(np.dot(X, weights))
        weights = weights + lr*(np.dot((y - y_hat), X)/X.shape[0])
        print(weights)
    return weights[:-1], weights[-1]
    
def sigmoid(z):
        return 1/ (1 + np.exp(-z))

coef_ , intercept_ = perceptron(X, y)
print(coef_,intercept_)

[1.11968009 0.954649   1.01266171]
[1.20914399 0.9155468  1.03134967]
[1.28112114 0.88059107 1.05285311]
[1.34163268 0.84870981 1.07573293]
[1.3940101  0.81927422 1.09924454]
[1.44029555 0.79187715 1.12296723]
[1.48183472 0.76623473 1.14664967]
[1.51956335 0.74213725 1.17013662]
[1.55415976 0.71942244 1.19333066]
[1.58613224 0.69795995 1.21617079]
[1.61587206 0.67764178 1.2386197 ]
[1.64368725 0.65837627 1.2606559 ]
[1.6698249  0.64008402 1.2822687 ]
[1.69448648 0.62269517 1.3034548 ]
[1.71783851 0.60614747 1.32421604]
[1.74002033 0.59038492 1.3445578 ]
[1.76114979 0.57535671 1.3644879 ]
[1.78132748 0.5610165  1.3840158 ]
[1.80064001 0.54732181 1.40315201]
[1.81916249 0.53423353 1.42190769]
[1.83696052 0.52171557 1.44029434]
[1.85409175 0.50973455 1.45832358]
[1.8706071  0.4982595  1.47600698]
[1.8865518  0.48726168 1.49335595]
[1.90196622 0.47671437 1.51038169]
[1.91688653 0.46659267 1.52709506]
[1.93134527 0.4568734  1.54350661]
[1.94537184 0.44753491 1.55962654]
[1.95899286 0.438557

In [185]:
def gd(X,y):
    
    X = np.insert(X,0,1,axis=1)
    weights = np.ones(X.shape[1])
    lr = 0.5
    for i in range(5000):
        y_hat = sigmoid(np.dot(X,weights))
        weights = weights + lr*(np.dot((y-y_hat),X)/X.shape[0])
        coef_ , intercept_ = weights[1:],weights[0]
    return coef_ , intercept_

def sigmoid(z):
    return 1/(1 + np.exp(-z))

hehehe = gd(X, y)
print(hehehe)



(array([-5085.90781993,  -142.86589978]), 153.18624019810352)


/var/folders/dh/6hv6grgx4jqd9v8dhxy0v5nh0000gn/T/ipykernel_46929/1365946042.py:13: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-z))


In [180]:
from sklearn.datasets import make_classification
import numpy as np
X, y = make_classification(n_samples=100, n_features=2, n_informative=1,n_redundant=0,
                           n_classes=2, n_clusters_per_class=1, random_state=41,hypercube=False,class_sep=20)
from sklearn.linear_model import LogisticRegression
lor = LogisticRegression(penalty='none',solver='sag')
lor.fit(X,y)
print(lor.coef_)
print(lor.intercept_)
m1 = -(lor.coef_[0][0]/lor.coef_[0][1])
b1 = -(lor.intercept_/lor.coef_[0][1])


[[4.81532166 0.21879572]]
[5.78214447]


/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [183]:
def __init__(self, lr=0.001, n=1000):
        self.lr = lr
        self.n = n
        self.weights = None
        self.intercept = None

def fit(self, X, y):
        # Add a column of ones to X for the bias (intercept) term
        X = np.insert(X, 0, 1, axis=1)
        
        # Initialize weights and intercept
        self.weights = np.zeros(X.shape[1])
        
        # Gradient Descent for fitting the model
        for _ in range(self.n):
            # Calculate the predicted probabilities
            y_pred = self._sigmoid(np.dot(X, self.weights))
            
            # Update weights (including the intercept)
            gradient = np.dot((y_pred - y), X) / X.shape[0]
            self.weights -= self.lr * gradient

        # Split weights and intercept
        self.intercept = self.weights[0]
        self.weights = self.weights[1:]
        
def predict(self, X):
        # Add the bias term (column of ones) to X
        X = np.insert(X, 0, 1, axis=1)
        
        # Predict probabilities
        y_pred_prob = self._sigmoid(np.dot(X, np.insert(self.weights, 0, self.intercept)))
        
        # Convert probabilities to binary outcomes (0 or 1)
        return [1 if prob > 0.5 else 0 for prob in y_pred_prob]

def _sigmoid(self, X):
        # Sigmoid function to map predictions to probabilities
    return 1 / (1 + np.exp(-X))

In [184]:
fit(X,y)

TypeError: fit() missing 1 required positional argument: 'y'